### PR TITLE
Feature - control branches on which to generate a change log.

### PR DESCRIPTION
**Pull request by newbish**
Disable building of change log for specified branches while still performing the other release functionality. resolves ​#156, resolves ​#51

### CODE REVIEW

**Comment by newbish** [comment]
Requesting a review from @pvdlg or another maintainer.

**Comment by kunish** [comment]
Why not just use array instead of comma separated string on `ignoreBranches`, while we are using json as configuration.

**Comment by kkikta-bcg** [comment]
> Why not just use array instead of comma separated string on `ignoreBranches`, while we are using json object as configuration parameter?

happy to make that change, especially if it gets this feature merged

**Comment by kingphil** [comment]
I could use this feature. How would you feel about the option being "branches: [...]" (as opposed to ignoreBranches)? This would have symmetry with the top-level "branches" array in .releaserc. I imagine the repos that would use this would have a list in mind where they do want the changelog modified, and a longer list of branches where they don't.

```
diff --git a/.releaserc.json b/.releaserc.json
index 094a34a..f5eb394 100644
--- a/.releaserc.json
+++ b/.releaserc.json
@@ -6,6 +6,7 @@
       "@semantic-release/changelog",
       {
         "changelogFile": "CHANGELOG.md",
+        "branches": ["master"]
       }
     ],
```

**Comment by newbish** [comment]
requesting review by a maintainer, @gr2m perhaps?

**Comment by newbish** [comment]
Resolves #156

**Comment by Roseidon** [comment]
Why did you close it? Is it done or don't you want to wait for approvals anymore? 🙈

**Comment by newbish** [comment]
> Why did you close it? Is it done or don't you want to wait for approvals anymore? 🙈

Realized it wasn't working the way I wanted it to. So did some rewrite since I needed it working and wanted to get a version in NPM ;) 

https://www.npmjs.com/package/@newbish/changelog

**Comment by newbish** [comment]
Feel free to test it out and see if it meets your needs, I was using this repo to test:
https://github.com/newbish/changelog-test

**Comment by leandrocrs** [comment]
Hi everyone! Any reviewer to take a look into this?

**Review by alexsanderp — APPROVED** [review]

**Comment by newbish** [comment]
@alexsanderp do you mind taking another look?

**Comment by Silthus** [comment]
I feel like having the option to filter all plugins by `branches:[...]` would be a good thing.

Is this also possible with this PR  or does it only work with the changelog plugin?

**Comment by newbish** [comment]
> I feel like having the option to filter all plugins by `branches:[...]` would be a good thing.
> 
> Is this also possible with this PR or does it only work with the changelog plugin?

This only affects the changelog, I believe the other plugins would have to implement something similar to have that capability.

**Comment by Silthus** [comment]
> This only affects the changelog, I believe the other plugins would have to implement something similar to have that capability.

Do you think there is some way to implement this for all plugins at once in the core library?

**Comment by newbish** [comment]
@alexsanderp can you please re-review this PR

**Comment by newbish** [comment]
@gr2m would you be able to provide a review?

**Review by leandrocrs — APPROVED** [review]
I believe some changes to files formatting could be out by this time.

**Comment by newbish** [comment]
> I believe some changes to files formatting could be out by this time.

attempted to apply prettier to match current formatting.

**Comment by mario-jerkovic** [comment]
@newbish awesome PR 🎉
@alexsanderp it is possible that we merge this PR, it would be really awesome 🙏🏼

**Comment by newbish** [comment]
@travi would you by chance be able to provide a review?

**Comment by newbish** [comment]
Anyone from the semantic-release team? @boennemann @UziTech @keplersj @kbrandwijk

**Comment by UziTech** [comment]
LGTM but I don't have write permission for this repo.

**Review by alexsanderp — APPROVED** [review]

**Comment by newbish** [comment]
@alexsanderp for the approval, however, looks like it requires maintainer approval.

**Comment by mgolawski** [comment]
Hey, is it going to be merged?

**Comment by newbish** [comment]
> LGTM but I don't have write permission for this repo.

any chance you can tell who has maintainer?

**Comment by eLarocque** [comment]
> > LGTM but I don't have write permission for this repo.
> 
> any chance you can tell who has maintainer?

When looking at previously closed PRs, you can see one was closed and approved by @travi in 2021

Dunno of he's still a maintainer but might be worth a shot

**Comment by travi** [comment]
i'm sorry that there hasn't been much maintainer activity on this thread, but our maintenance team has been very busy and unable to keep up with all of the activity across the projects. 

i think it is important to point to a few key points from our contributing guide:
* https://github.com/semantic-release/semantic-release/blob/ab45ab1f8d0d0f728fb026a92ec191bcc88f51f1/CONTRIBUTING.md?plain=1#L55
* https://github.com/semantic-release/semantic-release/blob/ab45ab1f8d0d0f728fb026a92ec191bcc88f51f1/CONTRIBUTING.md?plain=1#L68

in the various threads that are linked from this PR, i do not find any mention of this feature request being approved by a maintainer. i also do not find any responses to maintainer questions for clarification around why the feature is needed for supported workflows. instead the described desire details workflows that are not officially supported uses of the pre-release workflow functionality. pre-releases are intended for situations like confirming a breaking api change or _rare_ changes that cannot be tested in isolation because of built tool changes or similar. pre-releases are _not_ intended to be used to enable workflows similar to gitflow where every change starts as a pre-release to enable verification through the package consumers before promoting to the stable release line. keep in mind that semantic-release is not a generic workflow tool, but an opinionated tool that is intended to encourage continuous deployment style practices and simplify _semantic_ versioning and the communication of the impact of those changes. even if we were targeting a more generic workflow tool, decisions have to be made to keep the project maintainable.

as mentioned, our maintenance team has not been able to keep up with all activity, so we have to make decisions around priority. unsupported usage naturally gets prioritized lower than supported usage. without the information requested in our contributing guide, we are left to assume that the request is to enable unsupported workflows like i describe above. we have not closed this PR because we are not deciding yet that this will never be implemented, but it is being treated as lower priority based on the information we currently have. if the assumptions are being made with incomplete/incorrect information, the next step should be to provide a more complete description of the desired use case and why it falls within the supported workflows. in order for a change like this one to move forward, the maintainers need to agree that it is valuable to the project and is worth the additional complexity and maintenance burden moving forward.

**Comment by travi** [comment]
since my previous comment has not resulted in new information that suggests that this request is releated to _supported_ workflows, i think it is time to close this PR along with https://github.com/semantic-release/changelog/issues/156#issuecomment-1427067931. 

if there is desire to re-open the conversation in the furture, please feel free to open a new issue thread. please consider our contribution guidelines in that effert by understanding that the first step needs to be gaining alignment from maintainers about the value of the addition. if the desire is to enable a gitflow-like workflow, it will likely be difficult to gain such alignment. regardless, we would prefer to save contributors the effort of preparing a PR if that alignment has not yet been reached.

**Pull request closed without merging**
